# syntax=docker/dockerfile:1.7
#
# MAI runtime image — CPU only, x86_64-linux.
# DOUGHERTY lane J-04 (docs/dougherty/JOHN-REMEDIATION-PLAN.md §3 W2).
# Closes GitDoctor CFG-007 (no Dockerfile for containerization).
#
# Scope of THIS Dockerfile:
#   * Builds the mai-api and mai-ship-validate binaries from the
#     mai-api crate using the workspace-pinned Rust toolchain (1.85).
#   * Stages Python adapter runtime dependencies from requirements-lock.txt
#     (the hashed lock produced by J-03 via pip-compile).
#   * Final image is distroless cc-debian12:nonroot — no shell, no
#     package manager, runs as uid 65532. This is intentional: the
#     MAI core is air-gapped and should not be shell-debuggable in
#     production.
#
# OUT OF SCOPE (deliberately, not by oversight):
#   * GPU runtime. No CUDA, no ROCm, no Metal. Inference adapters
#     pointed at GPU backends (vLLM, TGI, TensorRT-LLM, ExLlamaV2)
#     will fail at adapter init in this image. CPU-only smoke is the
#     intent. A GPU image is a separate future session.
#   * Multi-arch. x86_64 only. ARM64 deployments require a separate
#     build with arm64 base pins.
#   * The Node MCP integrity server. That tooling is for the build
#     side, not the runtime; it lives in .integrity/mcp-server/ and
#     is not shipped in the container.
#
# Base-image pinning policy:
#   All base images below are pinned to linux/amd64 manifest digests.
#   This matches the x86_64-only scope declared above and closes
#   GitDoctor CFG-002 for reproducible container bases.
#
# Manual verify command (Docker required; verified end-to-end in
# DOUGHERTY J-04, image lands at ~53 MB):
#   docker buildx build --progress=plain -t mai-rc1:dockerfile-test mai/
#   docker run -d --name mai-smoke -p 8420:8420 -p 8421:8421 \
#       mai-rc1:dockerfile-test
#   # NOTE: the binary binds to 127.0.0.1 INSIDE the container by
#   # default (config-controlled via the Scout-tier defaults). To
#   # reach /v1/health from the host you must either supply a
#   # MAI_SHIP_PROFILE with `bind = "0.0.0.0"` OR exec into the
#   # container's network namespace:
#   docker run --rm --network container:mai-smoke curlimages/curl:latest \
#       http://localhost:8420/v1/health
#   docker stop mai-smoke && docker rm mai-smoke
#
# Regenerate lock files first (J-03 policy doc has the commands):
#   python -m piptools compile --generate-hashes --output-file=requirements-lock.txt pyproject.toml
#   (Cargo.lock and .integrity/mcp-server/package-lock.json are
#    regenerated by their own toolchains; see docs/LOCK-FILE-POLICY.md)

# ----------------------------------------------------------------------
# Stage 1: rust-builder
# ----------------------------------------------------------------------
FROM rust:1.88-slim-bookworm@sha256:a6cab604fa016ac022e78c24038497eb7617ab59150ca4c3dd2ede0fbd514d4b AS rust-builder

# Build-time deps for native crates and code generators:
#   pkg-config + libssl-dev — generic C toolchain glue for ring/blake3/etc.
#   ca-certificates         — TLS roots for crate registry fetch
#   protobuf-compiler       — protoc, required by mai-api/build.rs which
#                             drives tonic-build / prost-build over the
#                             gRPC .proto files
# Kept minimal — no curl, no git.
RUN apt-get update && apt-get install -y --no-install-recommends \
        pkg-config \
        libssl-dev \
        ca-certificates \
        protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

# Copy workspace manifest + lock + every crate's Cargo.toml first to
# maximise the Docker layer cache for the registry fetch. Source is
# copied in the next step.
COPY Cargo.toml Cargo.lock ./
COPY mai-core/Cargo.toml      mai-core/Cargo.toml
COPY mai-hil/Cargo.toml       mai-hil/Cargo.toml
COPY mai-adapters/Cargo.toml  mai-adapters/Cargo.toml
COPY mai-api/Cargo.toml       mai-api/Cargo.toml
COPY mai-sdk-rs/Cargo.toml    mai-sdk-rs/Cargo.toml
COPY mai-vault/Cargo.toml     mai-vault/Cargo.toml
COPY mai-agent/Cargo.toml     mai-agent/Cargo.toml
COPY mai-scheduler/Cargo.toml mai-scheduler/Cargo.toml
COPY mai-router/Cargo.toml    mai-router/Cargo.toml
COPY mai-compliance/Cargo.toml mai-compliance/Cargo.toml
COPY tools/pkg-builder/Cargo.toml tools/pkg-builder/Cargo.toml
COPY tools/rule-tester/Cargo.toml tools/rule-tester/Cargo.toml
COPY tools/mai-admin/Cargo.toml   tools/mai-admin/Cargo.toml

# Now copy source. The cache mount on /usr/local/cargo/registry keeps
# the crate index between rebuilds.
COPY mai-core      mai-core
COPY mai-hil       mai-hil
COPY mai-adapters  mai-adapters
COPY mai-api       mai-api
COPY mai-sdk-rs    mai-sdk-rs
COPY mai-vault     mai-vault
COPY mai-agent     mai-agent
COPY mai-scheduler mai-scheduler
COPY mai-router    mai-router
COPY mai-compliance mai-compliance
COPY tools         tools
COPY config        config

# Build both binaries in the mai-api crate. The release profile is
# the one acquirer reviewers exercise; debug builds are not shipped.
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/build/target \
    cargo build --release -p mai-api \
    && mkdir -p /out \
    && cp target/release/lamprey-mai-api          /out/mai-api \
    && cp target/release/lamprey-mai-ship-validate /out/mai-ship-validate

# ----------------------------------------------------------------------
# Stage 2: python-builder
# ----------------------------------------------------------------------
FROM python:3.12-slim-bookworm@sha256:42ada43c4265e1ed6db62ad8df62af99a4abb9a9d49622032522ac76efb0bcef AS python-builder

WORKDIR /pybuild

# Install runtime Python deps with hashes, no transitive resolution
# (everything is already pinned in the lock file).
COPY requirements-lock.txt requirements-lock.txt
RUN pip install --no-cache-dir --no-deps --require-hashes \
        --target=/python-deps -r requirements-lock.txt

# ----------------------------------------------------------------------
# Stage 3: runtime (distroless)
# ----------------------------------------------------------------------
# Distroless cc image has the C runtime + glibc that the Rust binary
# needs, plus a Python 3.12 interpreter is NOT in this image. The
# adapter runner is Python — for that we either run Python from a
# different image (recommended for production) OR add a python-slim
# runtime layer. For CPU-only smoke this image stays distroless and
# the adapters are loaded by spawning a separate Python container.
# A future session may produce a combined runtime if there is
# operational demand.
FROM gcr.io/distroless/cc-debian12:nonroot@sha256:7f376818a75cc40e78ea271a2f96102377059e5e860cf4b0253d886b5e3a9034 AS runtime

# Copy the two Rust binaries from stage 1.
COPY --from=rust-builder /out/mai-api          /usr/local/bin/mai-api
COPY --from=rust-builder /out/mai-ship-validate /usr/local/bin/mai-ship-validate

# Copy the static config templates so the operator can mount a
# profile and the binary can find the schema.
COPY --from=rust-builder /build/config /opt/mai/config

# Document the network surface. Default REST port is 8420, gRPC is
# 8421 — both bind to 127.0.0.1 inside the binary by default, so an
# operator must publish them with explicit -p host:container.
EXPOSE 8420 8421

USER nonroot:nonroot

# MAI_SHIP_PROFILE governs production hardening (auth, vault, air-gap
# enforcement). It is INTENTIONALLY left UNSET in this image — the
# Rust code distinguishes "unset" (boot in Scout-tier dev mode) from
# "set to empty string or a bad path" (fail-fast with a config error).
# Production deployments MUST supply a profile at runtime, e.g.:
#   docker run -e MAI_SHIP_PROFILE=/opt/mai/config/ship.toml ...
# See .env.example for the policy.

# The default invocation runs the server. mai-ship-validate is
# available on PATH for ad-hoc preflight checks via
#   docker run --rm --entrypoint mai-ship-validate <image> --help
ENTRYPOINT ["/usr/local/bin/mai-api"]
