# syntax=docker/dockerfile:1.7
#
# MAI runtime image — CPU only, x86_64-linux.
# DOUGHERTY lane J-04 (docs/dougherty/JOHN-REMEDIATION-PLAN.md §3 W2).
# Closes GitDoctor CFG-007 (no Dockerfile for containerization).
#
# Scope of THIS Dockerfile:
#   * Builds the mai-api and mai-ship-validate binaries from the
#     mai-api crate using the workspace-pinned Rust toolchain (1.85).
#   * Stages Python adapter runtime dependencies from requirements-lock.txt
#     (the hashed lock produced by J-03 via pip-compile).
#   * Final image is distroless cc-debian12:nonroot — no shell, no
#     package manager, runs as uid 65532. This is intentional: the
#     MAI core is air-gapped and should not be shell-debuggable in
#     production.
#
# OUT OF SCOPE (deliberately, not by oversight):
#   * GPU runtime. No CUDA, no ROCm, no Metal. Inference adapters
#     pointed at GPU backends (vLLM, TGI, TensorRT-LLM, ExLlamaV2)
#     will fail at adapter init in this image. CPU-only smoke is the
#     intent. A GPU image is a separate future session.
#   * Multi-arch. x86_64 only. ARM64 deployments require a separate
#     build with arm64 base pins.
#   * The Node MCP integrity server. That tooling is for the build
#     side, not the runtime; it lives in .integrity/mcp-server/ and
#     is not shipped in the container.
#
# Base-image pinning policy:
#   The tags below (rust:1.85-slim-bookworm, python:3.12-slim-bookworm,
#   gcr.io/distroless/cc-debian12:nonroot) are tag pins, not digest
#   pins. Tag pinning matches the project's current reproducibility
#   posture (Cargo.lock + requirements-lock.txt + package-lock.json
#   pin every internal dep). A follow-up session may convert these to
#   sha256 digests if a fully air-gapped build pipeline requires it.
#
# Manual verify command (Docker required):
#   docker buildx build --progress=plain -t mai-rc1:dockerfile-test mai/
#   docker run --rm -p 8420:8420 -p 8421:8421 \
#       -e MAI_SHIP_PROFILE=/opt/mai/config/dev.toml \
#       mai-rc1:dockerfile-test
#   curl http://localhost:8420/health
#
# Regenerate lock files first (J-03 policy doc has the commands):
#   python -m piptools compile --generate-hashes --output-file=requirements-lock.txt pyproject.toml
#   (Cargo.lock and .integrity/mcp-server/package-lock.json are
#    regenerated by their own toolchains; see docs/LOCK-FILE-POLICY.md)

# ----------------------------------------------------------------------
# Stage 1: rust-builder
# ----------------------------------------------------------------------
FROM rust:1.85-slim-bookworm AS rust-builder

# Build-time deps for native crates that may need a C toolchain
# (blake3 SIMD, ring, etc.). Kept minimal — no curl, no git.
RUN apt-get update && apt-get install -y --no-install-recommends \
        pkg-config \
        libssl-dev \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

# Copy workspace manifest + lock + every crate's Cargo.toml first to
# maximise the Docker layer cache for the registry fetch. Source is
# copied in the next step.
COPY Cargo.toml Cargo.lock ./
COPY mai-core/Cargo.toml      mai-core/Cargo.toml
COPY mai-hil/Cargo.toml       mai-hil/Cargo.toml
COPY mai-adapters/Cargo.toml  mai-adapters/Cargo.toml
COPY mai-api/Cargo.toml       mai-api/Cargo.toml
COPY mai-sdk-rs/Cargo.toml    mai-sdk-rs/Cargo.toml
COPY mai-vault/Cargo.toml     mai-vault/Cargo.toml
COPY mai-agent/Cargo.toml     mai-agent/Cargo.toml
COPY mai-scheduler/Cargo.toml mai-scheduler/Cargo.toml
COPY mai-router/Cargo.toml    mai-router/Cargo.toml
COPY mai-compliance/Cargo.toml mai-compliance/Cargo.toml
COPY tools/pkg-builder/Cargo.toml tools/pkg-builder/Cargo.toml
COPY tools/rule-tester/Cargo.toml tools/rule-tester/Cargo.toml
COPY tools/mai-admin/Cargo.toml   tools/mai-admin/Cargo.toml

# Now copy source. The cache mount on /usr/local/cargo/registry keeps
# the crate index between rebuilds.
COPY mai-core      mai-core
COPY mai-hil       mai-hil
COPY mai-adapters  mai-adapters
COPY mai-api       mai-api
COPY mai-sdk-rs    mai-sdk-rs
COPY mai-vault     mai-vault
COPY mai-agent     mai-agent
COPY mai-scheduler mai-scheduler
COPY mai-router    mai-router
COPY mai-compliance mai-compliance
COPY tools         tools
COPY config        config

# Build both binaries in the mai-api crate. The release profile is
# the one acquirer reviewers exercise; debug builds are not shipped.
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/build/target \
    cargo build --release -p mai-api \
    && mkdir -p /out \
    && cp target/release/mai-api          /out/mai-api \
    && cp target/release/mai-ship-validate /out/mai-ship-validate

# ----------------------------------------------------------------------
# Stage 2: python-builder
# ----------------------------------------------------------------------
FROM python:3.12-slim-bookworm AS python-builder

WORKDIR /pybuild

# Install runtime Python deps with hashes, no transitive resolution
# (everything is already pinned in the lock file).
COPY requirements-lock.txt requirements-lock.txt
RUN pip install --no-cache-dir --no-deps --require-hashes \
        --target=/python-deps -r requirements-lock.txt

# ----------------------------------------------------------------------
# Stage 3: runtime (distroless)
# ----------------------------------------------------------------------
# Distroless cc image has the C runtime + glibc that the Rust binary
# needs, plus a Python 3.12 interpreter is NOT in this image. The
# adapter runner is Python — for that we either run Python from a
# different image (recommended for production) OR add a python-slim
# runtime layer. For CPU-only smoke this image stays distroless and
# the adapters are loaded by spawning a separate Python container.
# A future session may produce a combined runtime if there is
# operational demand.
FROM gcr.io/distroless/cc-debian12:nonroot AS runtime

# Copy the two Rust binaries from stage 1.
COPY --from=rust-builder /out/mai-api          /usr/local/bin/mai-api
COPY --from=rust-builder /out/mai-ship-validate /usr/local/bin/mai-ship-validate

# Copy the static config templates so the operator can mount a
# profile and the binary can find the schema.
COPY --from=rust-builder /build/config /opt/mai/config

# Document the network surface. Default REST port is 8420, gRPC is
# 8421 — both bind to 127.0.0.1 inside the binary by default, so an
# operator must publish them with explicit -p host:container.
EXPOSE 8420 8421

USER nonroot:nonroot

# MAI_SHIP_PROFILE is the only mandatory runtime env var. Without it,
# mai-api starts in dev mode with permissive defaults that are NOT
# safe for production. See .env.example.
ENV MAI_SHIP_PROFILE=""

# The default invocation runs the server. mai-ship-validate is
# available on PATH for ad-hoc preflight checks via
#   docker run --rm --entrypoint mai-ship-validate <image> --help
ENTRYPOINT ["/usr/local/bin/mai-api"]
