"""Compute KV reuse-probability calibration coefficients from session data.

Given a session-level trace (output of `reconstruct.py`), this tool derives the
`reuse_alpha` (frequency weight) and `reuse_beta` (recency weight) coefficients
that the KV manager uses for eviction scoring. The defaults baked into
`config/kv.toml` were chosen heuristically; this tool replaces them with values
that match the actual observed traffic.

The model:

  reuse_score(session) = alpha * normalize(request_count) + beta * normalize(1 / gap)

Where:
  - `alpha` is calibrated from the fraction of sessions that show repeat use
    (sessions with `request_count > 1`). Heavy repeat traffic → higher alpha.
  - `beta` is calibrated from the inter-request gap distribution. Tighter gaps
    (lower median) → higher beta. We compute beta as a saturating function of
    the inverse median gap, clamped to [0.1, 1.0] so the calibration cannot
    push either coefficient outside a sane range.

Usage:
    python calibrate.py <sessions.ndjson> [--out kv_calib.toml]
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path

ALPHA_FLOOR = 0.1
ALPHA_CEIL = 1.0
BETA_FLOOR = 0.1
BETA_CEIL = 1.0
GAP_REFERENCE_SECS = 30.0


def load_sessions(path: Path) -> list[dict]:
    sessions: list[dict] = []
    with path.open("r", encoding="utf-8") as src:
        for line_no, line in enumerate(src, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                sessions.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"line {line_no}: invalid JSON: {exc}") from exc
    return sessions


def calibrate(sessions: list[dict]) -> dict:
    if not sessions:
        return {
            "reuse_alpha": ALPHA_FLOOR,
            "reuse_beta": BETA_FLOOR,
            "sessions_observed": 0,
            "repeat_fraction": 0.0,
            "median_gap_secs": 0.0,
        }

    repeat = sum(1 for s in sessions if int(s.get("request_count", 0)) > 1)
    repeat_fraction = repeat / len(sessions)
    alpha = ALPHA_FLOOR + (ALPHA_CEIL - ALPHA_FLOOR) * repeat_fraction
    alpha = clamp(alpha, ALPHA_FLOOR, ALPHA_CEIL)

    gaps = [
        float(s.get("mean_gap_secs", 0.0))
        for s in sessions
        if float(s.get("mean_gap_secs", 0.0)) > 0
    ]
    median_gap = statistics.median(gaps) if gaps else 0.0
    if median_gap <= 0:
        beta = BETA_FLOOR
    else:
        beta = clamp(GAP_REFERENCE_SECS / (median_gap + GAP_REFERENCE_SECS), BETA_FLOOR, BETA_CEIL)

    return {
        "reuse_alpha": round(alpha, 4),
        "reuse_beta": round(beta, 4),
        "sessions_observed": len(sessions),
        "repeat_fraction": round(repeat_fraction, 4),
        "median_gap_secs": round(median_gap, 4),
    }


def clamp(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


def render_toml(result: dict) -> str:
    return (
        "# Generated by tools/trace-tools/calibrate.py\n"
        f"# sessions_observed = {result['sessions_observed']}\n"
        f"# repeat_fraction   = {result['repeat_fraction']}\n"
        f"# median_gap_secs   = {result['median_gap_secs']}\n"
        "\n"
        "[eviction]\n"
        f"reuse_alpha = {result['reuse_alpha']}\n"
        f"reuse_beta  = {result['reuse_beta']}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Calibrate KV reuse coefficients from session data."
    )
    parser.add_argument("sessions", type=Path, help="Session NDJSON input file.")
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Optional TOML output path. Prints to stdout if omitted.",
    )
    args = parser.parse_args(argv)

    if not args.sessions.exists():
        print(f"error: input {args.sessions} does not exist", file=sys.stderr)
        return 2

    sessions = load_sessions(args.sessions)
    result = calibrate(sessions)
    toml_text = render_toml(result)
    if args.out:
        args.out.write_text(toml_text, encoding="utf-8")
        print(f"wrote calibration to {args.out}")
    else:
        sys.stdout.write(toml_text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
