"""MAI Python SDK for IM-OS applications.

Provides typed client access to the MAI API for building L4-L5
applications on top of the Model Abstraction Interface.
"""

__version__ = "0.2.0"

from mai.client import AsyncMaiClient, MaiClient
from mai.config import MaiClientConfig
from mai.errors import (
    AirGapViolationError,
    AuthenticationError,
    BadRequestError,
    ClaimExpiredError,
    ConnectionError,  # noqa: A004 — intentional SDK shadow of builtin
    MaiError,
    NotFoundError,
    PermissionError,  # noqa: A004 — intentional SDK shadow of builtin
    PowerStateUnavailableError,
    RateLimitError,
    ServerError,
    TimeoutError,  # noqa: A004 — intentional SDK shadow of builtin
    TrustCacheStaleError,
)
from mai.retry import DEFAULT_RETRY_POLICY, NO_RETRY_POLICY, RetryPolicy
from mai.types import (
    AdapterHealthEntry,
    AirgapStatusResponse,
    AuditEntry,
    AuditLogResponse,
    BenchmarkResult,
    CapabilityInfo,
    ChatChoice,
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatMessage,
    CompletionRequest,
    CompletionResponse,
    ContentSafetyLevel,
    EmbeddingData,
    EmbeddingRequest,
    EmbeddingResponse,
    ErrorResponse,
    FinishReason,
    FunctionCallRequest,
    FunctionCallResponse,
    GpuHealthEntry,
    HardwareHealthResponse,
    HealthResponse,
    InstanceHealthResponse,
    InstanceMetricsResponse,
    ModelDetail,
    ModelDiscoverResponse,
    ModelInstallResponse,
    ModelLoadResponse,
    ModelObject,
    ModelRemoveResponse,
    ModelUnloadResponse,
    PowerStateResponse,
    PowerTransitionRequest,
    PowerTransitionResponse,
    ProfileObject,
    ProfilePermissions,
    ProfileRole,
    RequestPriority,
    RevocationStatusResponse,
    SchedulerAnomaliesResponse,
    SchedulerMetricsResponse,
    StructuredRequest,
    StructuredResponse,
    SystemHealthResponse,
    TrustBundleStatus,
    TrustClaim,
    UpdateCheckResponse,
    UpdateStatusResponse,
    Usage,
)

__all__ = [
    "DEFAULT_RETRY_POLICY",
    "NO_RETRY_POLICY",
    "AdapterHealthEntry",
    "AirGapViolationError",
    "AirgapStatusResponse",
    "AsyncMaiClient",
    # Audit types
    "AuditEntry",
    "AuditLogResponse",
    "AuthenticationError",
    "BadRequestError",
    "BenchmarkResult",
    "CapabilityInfo",
    "ChatChoice",
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "ChatMessage",
    "ClaimExpiredError",
    "CompletionRequest",
    "CompletionResponse",
    "ConnectionError",
    "ContentSafetyLevel",
    "EmbeddingData",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "ErrorResponse",
    "FinishReason",
    "FunctionCallRequest",
    "FunctionCallResponse",
    "GpuHealthEntry",
    "HardwareHealthResponse",
    "HealthResponse",
    "InstanceHealthResponse",
    "InstanceMetricsResponse",
    # Client
    "MaiClient",
    "MaiClientConfig",
    # Error types
    "MaiError",
    "ModelDetail",
    "ModelDiscoverResponse",
    "ModelInstallResponse",
    "ModelLoadResponse",
    "ModelObject",
    "ModelRemoveResponse",
    "ModelUnloadResponse",
    "NotFoundError",
    "PermissionError",
    "PowerStateResponse",
    "PowerStateUnavailableError",
    "PowerTransitionRequest",
    "PowerTransitionResponse",
    "ProfileObject",
    "ProfilePermissions",
    "ProfileRole",
    "RateLimitError",
    "RequestPriority",
    "RetryPolicy",
    "RevocationStatusResponse",
    "SchedulerAnomaliesResponse",
    "SchedulerMetricsResponse",
    "ServerError",
    "StructuredRequest",
    "StructuredResponse",
    "SystemHealthResponse",
    "TimeoutError",
    "TrustBundleStatus",
    "TrustCacheStaleError",
    "TrustClaim",
    "UpdateCheckResponse",
    "UpdateStatusResponse",
    "Usage",
]
